/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_login (void);
GtkWidget* create_menu (void);
GtkWidget* create_gestion_ouvrier (void);
GtkWidget* create_gestion_tropaux (void);
GtkWidget* create_gestion_equipement (void);
GtkWidget* create_gestion_client (void);
GtkWidget* create_gestion_capteur (void);
GtkWidget* create_gestion_agriculture (void);
GtkWidget* create_fiche_presence (void);
GtkWidget* create_gestion_admin (void);
GtkWidget* create_annee_seche (void);
GtkWidget* create_meilleur_ouvrier (void);
GtkWidget* create_pire_ouvrier (void);
GtkWidget* create_capteur_alarmante (void);
GtkWidget* create_marque_defectueuse (void);
GtkWidget* create_type_tropaux (void);
